version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into Docker Hub...
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

  build:
    commands:
      - echo Building frontend image...
      - cd frontend
      - docker build -t hrushant1909/sefinalproject-frontend:1.0.0 .
      - docker push hrushant1909/sefinalproject-frontend:1.0.0
      - cd ..

      - echo Building backend image...
      - cd backend
      - docker build -t hrushant1909/sefinalproject-backend:1.0.0 .
      - docker push hrushant1909/sefinalproject-backend:1.0.0
      - cd ..

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - docker-compose.yml